version: "3.9"

services:
  db:
    image: postgres:16
    container_name: platform_app_postgres
    restart: always
    environment:
      POSTGRES_DB: platform_app_db
      POSTGRES_USER: platform_user
      POSTGRES_PASSWORD: platform_pass_9Q2m
    ports:
      - "5435:5432"
    volumes:
      - platform_app_db_data:/var/lib/postgresql/data

volumes:
  platform_app_db_data:
